server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# OpenAI Config
spring.ai.openai.api-key=
spring.ai.openai.chat.model=gpt-5.4
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=8192
spring.ai.openai.embedding.options.dimensions=768

# Embedding model
spring.ai.openai.embedding.options.model=text-embedding-3-small

# Pinecone Vector Store
spring.ai.vectorstore.pinecone.api-key=
spring.ai.vectorstore.pinecone.index-name=
spring.ai.vectorstore.pinecone.namespace=default

# Cloudinary
cloudinary.url=
cloudinary.pdf-folder=pdf-chat
cloudinary.cloud-name=dvwxun4vh

