server.port=8081


# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/finleydb

spring.datasource.username=root
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect

spring.jpa.hibernate.ddl-auto=none
#spring.jpa.show-sql=true
#spring.jpa.properties.hibernate.format_sql=true

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# OpenAI Config
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7

# Sets the maximum number of tokens/words the AI can generate in one response, increase for longer replies
spring.ai.openai.chat.options.max-tokens=1000
spring.ai.openai.embedding.options.dimensions=1536
spring.ai.openai.embedding.options.model=text-embedding-3-small


# Pinecone Vector Store
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=springai
spring.ai.vectorstore.pinecone.namespace=default


# Cloudinary
cloudinary.url=${CLOUDINARY_URL}
cloudinary.pdf-folder=pdf-chat
cloudinary.image-folder=image-chat
cloudinary.cloud-name=dvwxun4vh


#Enable Virtual Threads
spring.threads.virtual.enabled=true

# Task Execution with Virtual Threads (Optional)
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=500
