server.port=8080

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB

# OpenAI Config
spring.ai.openai.api-key=${OPENAI_API_KEY}
spring.ai.openai.chat.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=8192
spring.ai.openai.embedding.options.dimensions=1536

# Embedding model
spring.ai.openai.embedding.options.model=text-embedding-3-small

# Pinecone Vector Store
spring.ai.vectorstore.pinecone.api-key=${PINECONE_API_KEY}
spring.ai.vectorstore.pinecone.index-name=springai
spring.ai.vectorstore.pinecone.namespace=default

# Cloudinary
cloudinary.url=${CLOUDINARY_URL}
cloudinary.pdf-folder=pdf-chat
cloudinary.cloud-name=dvwxun4vh

