server.port=8081


# Database Configuration
spring.datasource.url=jdbc:mysql://localhost:3306/owleydb
spring.datasource.username=root
spring.datasource.password=project
spring.datasource.driver-class-name= com.mysql.cj.jdbc.Driver

# Hibernate Configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
# Enable multipart/form-data support for file uploads
spring.servlet.multipart.enabled=true
# Maximum size allowed for a single uploaded file
spring.servlet.multipart.max-file-size=8MB
# Maximum size allowed for the entire multipart request
spring.servlet.multipart.max-request-size=8MB

# OpenAI Config
spring.ai.openai.api-key=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
spring.ai.openai.chat.options.model=gpt-4o
spring.ai.openai.chat.options.temperature=0.7
spring.ai.openai.chat.options.max-tokens=8192
spring.ai.openai.embedding.options.dimensions=1536
spring.ai.openai.embedding.options.model=text-embedding-3-small


# Pinecone Vector Store
spring.ai.vectorstore.pinecone.api-key=pcsk_3moHXN_KgX8mprestdHvkuW5kWro56mYVgNV7KCaFu696FwQq2esysYUYtTU4yiwSZRbaN
spring.ai.vectorstore.pinecone.index-name=springai
spring.ai.vectorstore.pinecone.namespace=default


# Cloudinary
cloudinary.url=cloudinary://574868517867527:iVoGbIG5wCKack9B7Pur2AI510Y@dvwxun4vh
cloudinary.pdf-folder=pdf-chat
cloudinary.image-folder=image-chat
cloudinary.cloud-name=dvwxun4vh

#Enable Virtual Threads
spring.threads.virtual.enabled=true

# Task Execution with Virtual Threads (Optional)
spring.task.execution.pool.core-size=10
spring.task.execution.pool.max-size=100
spring.task.execution.pool.queue-capacity=500
